### ISSUE TITLE
hexo-action will removes the **.gihub.io repo commits history.

### ISSUE THREAD

**Issue by DeppWang** [sma11black/hexo-action#3]
hexo d:
1. copy the public folder file to the .deploy_git folder
2. commit
3. push 

If the repo without a .deploy_git folder(usually no), `hexo d` will create a new .deploy_git folder, so old commits history will be removed.

Can add this command in entrypoint.sh to solve this issue:
```
git clone https://github.com/username/username.github.io.git .deploy_git
```
Add a tips in the README.md?

**Comment by sma11black** [comment]
@DeppWang I did not consider adding this feature before because hexo's default commit message is `Site updated: {{ now('YYYY-MM-DD HH:mm:ss') }}`. This doesn't seem to make much sense. The user actually cares about the commit message of the *hexo source code repo*.

Now I still add this part. Thank you for your contribution. At the same time, I added an additional configuration item to make the commit message a little more meaningful. For details, please check the release info of [`v1.0.1`](https://github.com/sma11black/hexo-action/tree/v1.0.1).

*Some personal considerations*
I think that in the case of deleting an article, if you keep the commit history of the public *Github Pages repo*, there may be a **risk** of being retrieved by others. Some bloggers may not want this to happen. I still added this feature because the original publishing process also had this problem. Perhaps this is not a part of concern.

**Comment by DeppWang** [comment]
Thanks for your action.

**Comment by kevin7lou** [comment]
hi @sma11black @DeppWang ,

I think I encountered the same issue with @DeppWang . In the beginning, I could push the changes of `blog` source code repository to deploy them on `**.github.io`. But now, perhaps I run locally `hexo g & hexo s` for testing, I cannot commit and deploy the changes on `**.github.io` via Github Action.

Would you pls give some suggestions to fix it? Thanks a lot!

**Comment by DeppWang** [comment]
see see I blog article: https://depp.wang/2020/02/17/use-github-actions-to-achieve-hexo-blog-auto-deploy/

**Comment by sma11black** [comment]
@kevin7lou Do you mean that the generated static pages cannot be deployed to `**.github.io`? This question should not be related to your local testing. Can you attach an **error message** or **log** screenshot of running Github Action? Otherwise, it is difficult for me to determine where the problem is.

If this is not an issue where the commit history is overwritten, you should consider to open a **new issue**.

**Comment by Van1yu3** [comment]
Hi @sma11black ,
I totally agree with your personal considerations that some bloggers would not like to take risk keeping their commits history. What if I intentially want to clear my previous commits using this action? Would you add an option to this setting?

Thanks!

**Comment by sma11black** [comment]
@Van1yu3 You can use [v1.0.4](https://github.com/sma11black/hexo-action/tree/v1.0.4) now.
Example workflow:
```yaml
- name: Deploy
  id: deploy
  uses: sma11black/hexo-action@v1.0.4
  with:
    ...
    commit_msg: none
```
For details, see [README.md](https://github.com/sma11black/hexo-action/tree/v1.0.4#inputs).
